### ISSUE TITLE
MUSE link in Dockerfile not valid

### ISSUE THREAD

**Issue by Jeltje** [ucscCancer/pcawg_tools#10]
This is an issue with /tools/muse/Dockerfile

It looks like `http://odin.mdacc.tmc.edu/~yfan1/MuSE/MuSEv1.0rc_submission_74ca763` is no longer a valid URL. The current version is apparently
`http://odin.mdacc.tmc.edu/~yfan1/MuSE/MuSEv1.0rc_submission_b391201`

Differences between the versions are not documented, at least not under http://odin.mdacc.tmc.edu/~yfan1

**Comment by kellrott** [comment]
They added in a fail over in the case that the WGS model didn't work, it would try the WXS model. 
The new version got posted yesterday. 
We'll link against the official binary for 1.0 when they release it. (And hopefully they'll release the source after the publication).

**Comment by kellrott** [comment]
Fixed
